apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: devops-go
spec:
  selector: 
    matchLabels:
      app: devops-go
  replicas: 3 
  template: 
    metadata:
      labels:
        app: devops-go
    spec:
      containers:
      - name: devops-go
        image: nrt.ocir.io/ociobent/devops/go-hello:${BUILDRUN_HASH}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: devops-go